name: Pull request

on:
  pull_request:
    branches-ignore:
      - "releases/**"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run tests
        run: cargo test
